### ISSUE TITLE
How to get css file's style from object c? Is there a demo project?

### ISSUE THREAD

**Issue by gclsoft** [nolanw/HTMLReader#6]
``` css
.i-AED{background-position:0 0;}.i-ARS{background-position:-16px 0;}
```

I wanna get the css file's `.i-AED`'s `background-position` attribute in object-c code
